FROM webhippie/alpine:latest-arm32v6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT [""]

RUN apk update && \
  apk upgrade && \
  apk add openssh-client git git-lfs git-diff-highlight git-subtree git-crypt git-secret@testing && \
  rm -rf /var/cache/apk/*
