FROM webhippie/alpine:latest-amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]

RUN apk update && \
  apk upgrade && \
  apk add git git-lfs git-diff-highlight git-subtree git-secret git-crypt && \
  rm -rf /var/cache/apk/*
